"""
Licence key validator.

Validation order:
  1. Local SQLite DB  — keys generated by the webhook server (instant, no network)
  2. LemonSqueezy API — native LS licence keys (requires internet)

This means the system works for both locally-generated keys (created when a
webhook fires) and any native LS licence keys the customer may have.
"""
from __future__ import annotations

import logging

import requests

log = logging.getLogger(__name__)

_VALIDATE_URL = "https://api.lemonsqueezy.com/v1/licenses/validate"

# Maps capitalised tier name (from LS API) → internal plan key.
_TIER_TO_PLAN: dict[str, str] = {
    "Free":         "free",
    "Starter":      "starter",
    "Pro":          "professional",
    "Professional": "professional",
    "Premium":      "premium",
    "Enterprise":   "enterprise",
}


def validate_licence_key(licence_key: str) -> dict:
    """Validate a licence key.

    Returns {"valid": bool, "tier": str, "plan": str, "error": str | None}

    `tier` is the capitalised display name (e.g. "Professional").
    `plan` is the internal plan key (e.g. "professional").
    """
    key = licence_key.strip() if licence_key else ""
    if not key:
        return {"valid": False, "tier": "Free", "plan": "free", "error": None}

    # ── 1. Check local DB first ───────────────────────────────────────────
    try:
        from services.licence_manager import validate_local_key
        local = validate_local_key(key)
        if local["valid"]:
            plan = local["plan"]
            # Capitalise for display
            tier = plan.capitalize() if plan != "professional" else "Professional"
            log.info("Licence validated locally: key=...%s plan=%s", key[-4:], plan)
            return {"valid": True, "tier": tier, "plan": plan, "error": None}
        # If found but inactive, surface the error immediately
        if local["error"]:
            return {"valid": False, "tier": "Free", "plan": "free", "error": local["error"]}
    except Exception as exc:
        log.warning("Local licence DB check failed: %s", exc)

    # ── 2. Fall back to LemonSqueezy API ─────────────────────────────────
    from config.lemonsqueezy_config import VARIANT_TIER_MAP

    try:
        resp = requests.post(_VALIDATE_URL, data={"license_key": key}, timeout=8)
        data = resp.json()
    except requests.Timeout:
        return {
            "valid": False, "tier": "Free", "plan": "free",
            "error": "Licence server timed out — please try again.",
        }
    except requests.RequestException as exc:
        log.warning("Licence server request failed: %s", exc)
        return {
            "valid": False, "tier": "Free", "plan": "free",
            "error": "Could not reach the licence server. Please check your connection and try again.",
        }

    if not data.get("valid"):
        return {
            "valid": False, "tier": "Free", "plan": "free",
            "error": data.get("error") or "Invalid or expired licence key.",
        }

    variant_id = str(data.get("meta", {}).get("variant_id", ""))
    tier = VARIANT_TIER_MAP.get(variant_id, "Professional")
    plan = _TIER_TO_PLAN.get(tier, "professional")

    log.info("Licence validated via LS API: variant_id=%s tier=%s", variant_id, tier)
    return {"valid": True, "tier": tier, "plan": plan, "error": None}
