import pandas as pd
from datetime import datetime
import os


class ReportBuilder:
    def __init__(self, config):
        self.config = config

    def build_report(self, raw_df, cleaned_df, log_df, quality_df, dictionary_df=None):
        timestamp = datetime.now().strftime("%Y%m%d_%H%M")
        file_name = f"ColtraDataAi_Cleaned_Report_{timestamp}.xlsx"

        with pd.ExcelWriter(file_name, engine="xlsxwriter") as writer:
            workbook = writer.book
            self._create_formats(workbook)

            # Sheets
            self._build_cover_sheet(workbook, writer, raw_df)
            self._write_dataframe(writer, raw_df, "Raw Data")
            self._write_dataframe(writer, cleaned_df, "Cleaned Data")
            self._write_dataframe(writer, log_df, "Cleaning Log")
            self._write_quality_sheet(writer, quality_df)

            if dictionary_df is not None:
                self._write_dataframe(writer, dictionary_df, "Data Dictionary")

            self._build_processing_notes(workbook)
            self._build_dashboard_sheet(workbook, raw_df, cleaned_df, quality_df)

        return file_name

    def _create_formats(self, workbook):
        self.title_format = workbook.add_format({
            "bold": True,
            "font_size": 20,
            "font_color": self.config["primary_colour"],
            "align": "left",
            "valign": "vcenter"
        })

        self.subtitle_format = workbook.add_format({
            "font_size": 11,
            "font_color": "#444444",
            "italic": True
        })

        self.section_header = workbook.add_format({
            "bold": True,
            "font_size": 12,
            "font_color": "white",
            "bg_color": self.config["primary_colour"],
            "border": 1,
            "align": "left",
            "valign": "vcenter"
        })

        self.table_header = workbook.add_format({
            "bold": True,
            "bg_color": self.config["header_fill"],
            "font_color": self.config["primary_colour"],
            "border": 1,
            "text_wrap": True
        })

        self.body_format = workbook.add_format({
            "border": 1,
            "valign": "top"
        })

        self.note_format = workbook.add_format({
            "font_size": 10,
            "font_color": "#555555",
            "italic": True,
            "text_wrap": True
        })

        self.metric_label = workbook.add_format({
            "bold": True,
            "bg_color": self.config["neutral_fill"],
            "border": 1
        })

        self.metric_value = workbook.add_format({
            "bold": True,
            "font_color": self.config["primary_colour"],
            "border": 1
        })

        self.success_format = workbook.add_format({
            "bold": True,
            "font_color": "white",
            "bg_color": self.config["success_colour"],
            "align": "center",
            "border": 1
        })

        self.warning_format = workbook.add_format({
            "bold": True,
            "font_color": "black",
            "bg_color": self.config["warning_colour"],
            "align": "center",
            "border": 1
        })

        self.danger_format = workbook.add_format({
            "bold": True,
            "font_color": "white",
            "bg_color": self.config["danger_colour"],
            "align": "center",
            "border": 1
        })

        self.disclaimer_format = workbook.add_format({
            "font_size": 9,
            "italic": True,
            "font_color": "#666666",
            "text_wrap": True
        })

    def _build_cover_sheet(self, workbook, writer, raw_df):
        sheet = workbook.add_worksheet("Report Summary")

        # Widths
        sheet.set_column("A:A", 4)
        sheet.set_column("B:B", 18)
        sheet.set_column("C:H", 18)

        # Optional logo
        logo_path = "assets/logo/coltradata_logo.png"
        if os.path.exists(logo_path):
            sheet.insert_image("B2", logo_path, {"x_scale": 0.45, "y_scale": 0.45})

        sheet.merge_range("B6:H6", self.config["app_name"], self.title_format)
        sheet.merge_range("B7:H7", self.config["tagline"], self.subtitle_format)

        sheet.write("B10", "Generated On", self.metric_label)
        sheet.write("C10", datetime.now().strftime("%d/%m/%Y %H:%M"), self.metric_value)

        sheet.write("B11", "Total Rows", self.metric_label)
        sheet.write("C11", len(raw_df), self.metric_value)

        sheet.write("B12", "Total Columns", self.metric_label)
        sheet.write("C12", len(raw_df.columns), self.metric_value)

        sheet.merge_range(
            "B15:H18",
            "This workbook contains the original uploaded data, cleaned data output, processing log, quality checks and dashboard reporting generated by ColtraDataAi.",
            self.body_format
        )

        sheet.merge_range(
            "B21:H22",
            "ColtraDataAi provides structured data cleaning, validation and dashboard reporting outputs. It does not provide advisory or decision-making recommendations.",
            self.disclaimer_format
        )

        sheet.write("B24", "Contact", self.metric_label)
        sheet.write("C24", self.config["contact_email"], self.metric_value)

    def _write_dataframe(self, writer, df, sheet_name):
        df.to_excel(writer, sheet_name=sheet_name, startrow=1, index=False)

        workbook = writer.book
        worksheet = writer.sheets[sheet_name]

        # Header formatting
        for col_num, value in enumerate(df.columns.values):
            worksheet.write(1, col_num, value, self.table_header)

        # Top title row
        worksheet.write(0, 0, sheet_name, self.section_header)

        # Freeze panes
        worksheet.freeze_panes(2, 0)

        # Autofilter
        worksheet.autofilter(1, 0, len(df) + 1, max(len(df.columns) - 1, 0))

        # Column widths
        for i, col in enumerate(df.columns):
            series = df[col].astype(str)
            max_len = max(
                [len(str(col))] + series.head(200).map(len).tolist()
            )
            worksheet.set_column(i, i, min(max_len + 2, 28))

        # Conditional formatting for blanks
        if len(df.columns) > 0 and len(df) > 0:
            worksheet.conditional_format(
                2, 0, len(df) + 1, len(df.columns) - 1,
                {
                    "type": "blanks",
                    "format": workbook.add_format({"bg_color": "#FFF2CC"})
                }
            )

    def _write_quality_sheet(self, writer, quality_df):
        quality_df.to_excel(writer, sheet_name="Quality Checks", startrow=1, index=False)
        workbook = writer.book
        worksheet = writer.sheets["Quality Checks"]

        worksheet.write(0, 0, "Quality Checks", self.section_header)

        for col_num, value in enumerate(quality_df.columns.values):
            worksheet.write(1, col_num, value, self.table_header)

        worksheet.freeze_panes(2, 0)
        worksheet.autofilter(1, 0, len(quality_df) + 1, max(len(quality_df.columns) - 1, 0))
        worksheet.set_column("A:A", 26)
        worksheet.set_column("B:B", 16)

        # Optional visual highlight for status-style values if present
        if "Metric" in quality_df.columns and "Value" in quality_df.columns:
            worksheet.write("D2", "Overall Status", self.metric_label)

            missing_total = 0
            rows_total = 0

            try:
                if "Missing Values" in quality_df["Metric"].values:
                    missing_total = int(
                        quality_df.loc[quality_df["Metric"] == "Missing Values", "Value"].iloc[0]
                    )
                if "Rows" in quality_df["Metric"].values:
                    rows_total = int(
                        quality_df.loc[quality_df["Metric"] == "Rows", "Value"].iloc[0]
                    )
            except Exception:
                pass

            if missing_total == 0:
                worksheet.write("E2", "PASS", self.success_format)
            elif missing_total < max(50, rows_total * 0.05):
                worksheet.write("E2", "REVIEW", self.warning_format)
            else:
                worksheet.write("E2", "WARNING", self.danger_format)

    def _build_processing_notes(self, workbook):
        sheet = workbook.add_worksheet("Processing Notes")
        sheet.set_column("A:A", 100)

        sheet.write("A1", "Processing Notes", self.section_header)
        notes = [
            "This section records the assumptions and processing rules applied during report generation.",
            "",
            "Standard elements may include:",
            "- Duplicate handling",
            "- Whitespace trimming",
            "- Header standardisation",
            "- Missing value reporting",
            "- Dashboard summary generation",
            "",
            "This output is non-advisory and is provided for structured reporting purposes only."
        ]

        for idx, line in enumerate(notes, start=3):
            sheet.write(f"A{idx}", line, self.body_format if not line.startswith("-") else self.note_format)

    def _build_dashboard_sheet(self, workbook, raw_df, cleaned_df, quality_df):
        sheet = workbook.add_worksheet("Dashboard")

        # Set layout
        sheet.set_column("A:A", 24)
        sheet.set_column("B:B", 14)
        sheet.set_column("D:J", 12)

        sheet.write("A1", "Dashboard Reporting", self.section_header)

        # Summary cards area
        original_rows = len(raw_df)
        cleaned_rows = len(cleaned_df)
        removed_rows = original_rows - cleaned_rows
        total_columns = len(cleaned_df.columns)
        missing_values = int(cleaned_df.isnull().sum().sum())

        metrics = [
            ("Original Rows", original_rows),
            ("Cleaned Rows", cleaned_rows),
            ("Rows Removed", removed_rows),
            ("Columns", total_columns),
            ("Missing Values", missing_values),
        ]

        r = 3
        for label, value in metrics:
            sheet.write(r, 0, label, self.metric_label)
            sheet.write(r, 1, value, self.metric_value)
            r += 1

        # Chart source data: missing values by top columns
        missing_by_col = cleaned_df.isnull().sum().sort_values(ascending=False).head(10)
        start_row = 3
        sheet.write(start_row - 1, 3, "Top Columns by Missing Values", self.table_header)
        sheet.write(start_row - 1, 4, "Count", self.table_header)

        for i, (col_name, val) in enumerate(missing_by_col.items(), start=start_row):
            sheet.write(i, 3, str(col_name), self.body_format)
            sheet.write(i, 4, int(val), self.body_format)

        # Chart 1 - Missing values
        chart1 = workbook.add_chart({"type": "column"})
        chart1.add_series({
            "name": "Missing Values",
            "categories": ["Dashboard", start_row, 3, start_row + len(missing_by_col) - 1, 3],
            "values": ["Dashboard", start_row, 4, start_row + len(missing_by_col) - 1, 4],
            "fill": {"color": self.config["secondary_colour"]},
            "border": {"color": self.config["primary_colour"]}
        })
        chart1.set_title({"name": "Missing Values by Column"})
        chart1.set_legend({"none": True})
        chart1.set_y_axis({"major_gridlines": {"visible": False}})
        chart1.set_style(10)

        sheet.insert_chart("G3", chart1, {"x_scale": 1.15, "y_scale": 1.15})

        # Chart source data: row counts comparison
        compare_row = 18
        sheet.write(compare_row, 3, "Dataset Stage", self.table_header)
        sheet.write(compare_row, 4, "Rows", self.table_header)

        sheet.write(compare_row + 1, 3, "Original", self.body_format)
        sheet.write(compare_row + 1, 4, original_rows, self.body_format)

        sheet.write(compare_row + 2, 3, "Cleaned", self.body_format)
        sheet.write(compare_row + 2, 4, cleaned_rows, self.body_format)

        chart2 = workbook.add_chart({"type": "bar"})
        chart2.add_series({
            "name": "Rows",
            "categories": ["Dashboard", compare_row + 1, 3, compare_row + 2, 3],
            "values": ["Dashboard", compare_row + 1, 4, compare_row + 2, 4],
            "fill": {"color": self.config["primary_colour"]},
            "border": {"color": self.config["primary_colour"]}
        })
        chart2.set_title({"name": "Original vs Cleaned Rows"})
        chart2.set_legend({"none": True})
        chart2.set_x_axis({"major_gridlines": {"visible": False}})
        chart2.set_style(10)

        sheet.insert_chart("G18", chart2, {"x_scale": 1.15, "y_scale": 1.0})

        # Optional completeness ratio example
        completeness_row = 26
        sheet.write(completeness_row, 0, "Data Completeness", self.section_header)

        total_cells = cleaned_df.shape[0] * cleaned_df.shape[1] if cleaned_df.shape[0] > 0 and cleaned_df.shape[1] > 0 else 0
        complete_cells = total_cells - missing_values
        completeness_pct = round((complete_cells / total_cells) * 100, 2) if total_cells else 0

        sheet.write(completeness_row + 2, 0, "Completeness %", self.metric_label)
        sheet.write(completeness_row + 2, 1, completeness_pct, self.metric_value)
