branding = {
    "app_name":         "ColtraDataAi",
    "company":          "Coltrane Ltd",
    "version":          "2.0",
    "tagline":          "DATA. INSIGHTS. INTELLIGENCE.",
    "contact_email":    "support@coltradata.com",

    # Core palette
    "primary_colour":   "#1F4E79",
    "secondary_colour": "#D9E1F2",
    "accent_colour":    "#2E86AB",   # mid-blue accent for highlights and download buttons
    "header_fill":      "#D9E1F2",
    "neutral_fill":     "#F2F2F2",
    "light_fill":       "#F8FAFC",   # very light background for section containers

    # Status colours
    "success_colour":   "#46D324",
    "warning_colour":   "#F59E0B",
    "danger_colour":    "#DC2626",

    # Typography — used in PDF / ReportLab output
    "font_family":      "Helvetica",
    "font_family_bold": "Helvetica-Bold",

    # Assets
    "logo_path":        "assets/logo/coltradata_logo.png",

    # Standard non-advisory disclaimer applied to every report output
    "report_disclaimer": (
        "This document contains structured data cleaning and reporting outputs generated by "
        "ColtraDataAi. It does not constitute legal, financial, tax or compliance advice. "
        "Users remain responsible for reviewing all outputs and obtaining professional "
        "guidance where required."
    ),

    # Footer branding line for PDF page footers and report cover sheets
    "footer_line": "ColtraDataAi  ·  Coltrane Ltd  ·  support@coltradata.com",

    # UK trading-disclosure line (Companies (Trading Disclosures) Regulations 2008) —
    # company name, place of registration, registered number, and registered office
    # must appear on the website for a registered company.
    "legal_line": (
        "ColtraDataAi is a trading name of Coltrane Ltd, registered in England and Wales "
        "· Company No. 09088932 · Registered office: Kemp House, 128 City Road, "
        "London EC1V 2NX"
    ),

    # Extended chart palette — used across all Plotly figures for consistent colour sequencing
    "chart_palette": [
        "#1F4E79",   # primary dark blue
        "#2E86AB",   # accent mid-blue
        "#48C9B0",   # teal
        "#F4D03F",   # amber
        "#E67E22",   # orange
        "#D9E1F2",   # secondary light blue (for fills)
    ],
}
