"""Privacy, GDPR, cookies and terms text shown in the app's legal notices panel.

Mirrors the pattern in branding_config.py: all legal copy lives here so it can
be updated in one place and reused by any UI surface (footer expander,
exports, future legal pages) without duplicating text.
"""

legal = {
    "last_updated": "18 July 2026",
    "privacy_email": "privacy@coltradata.com",

    "data_controller": (
        "Coltrane Ltd (trading as ColtraDataAi), registered in England and Wales, "
        "Company No. 09088932, registered office: Kemp House, 128 City Road, "
        "London EC1V 2NX."
    ),

    "privacy_policy": (
        "**What we collect**\n\n"
        "- *Email address*: collected when you sign in. We use passwordless "
        "authentication — a one-time 6-digit code is sent to your email. No password "
        "is ever created or stored. The code itself is stored only as a one-way "
        "SHA-256 hash and expires after 10 minutes.\n"
        "- *Account profile*: on your first login after purchasing a plan, we ask for "
        "your name, company or organisation, and country (required), and optionally "
        "your phone number and VAT number. We also ask optional questions about your "
        "profession and industry to help us improve the product for your sector. "
        "No job titles, personal addresses beyond country, or sensitive categories of "
        "data are collected.\n"
        "- *Subscription data*: your plan tier, licence key, subscription status, and "
        "a count of how many times you have run the cleaning tool this month.\n"
        "- *Compliance consent records*: when you accept our Terms & Conditions and "
        "Privacy Policy, we record that acceptance along with a timestamp. If you "
        "opt in to marketing emails, we record that preference.\n"
        "- *Uploaded datasets*: processed entirely in memory for the duration of your "
        "browser session. Files are not written to disk or any database and are "
        "discarded when your session ends. We do not read, analyse, or retain the "
        "content of files you upload.\n\n"
        "**What we do not collect**\n\n"
        "Payment card numbers, bank account details, and all other financial "
        "transaction data are handled exclusively by our payment processor, "
        "Lemon Squeezy (operated by Link, LLC). ColtraDataAi never sees, "
        "receives, or stores any payment instrument data.\n\n"
        "**Why we collect it**\n\n"
        "- *Email and authentication data*: to verify your identity and provide "
        "secure access to the app (performance of a contract).\n"
        "- *Account profile and subscription data*: to administer your subscription, "
        "enforce plan limits, and provide the service you have paid for "
        "(performance of a contract).\n"
        "- *Profession and industry data*: to understand which sectors use "
        "ColtraDataAi and to prioritise product improvements that serve those "
        "sectors. This data is always aggregated and anonymised for internal "
        "analysis — individual records are never shared externally "
        "(legitimate interests).\n"
        "- *Marketing opt-in*: to send you product updates and tips, only if you "
        "explicitly opted in (consent).\n"
        "- *Uploaded dataset processing*: performed at your direction to deliver the "
        "cleaning and reporting output you requested. We act on your instructions "
        "and do not independently use that data for any other purpose.\n\n"
        "**Who else sees it**\n\n"
        "- *Lemon Squeezy / Link, LLC* — payment processing and subscription "
        "management. They receive your email and billing details at checkout. "
        "See lemonsqueezy.com/privacy.\n"
        "- *Supabase* — our database provider, used to store subscription, profile, "
        "and authentication data. Data is hosted in the EU (eu-west-1 region). "
        "See supabase.com/privacy.\n"
        "- *Render* — our application hosting provider. The app runs on Render "
        "infrastructure. See render.com/privacy.\n"
        "- *Resend* — used to deliver OTP verification codes and licence key emails "
        "to your email address. See resend.com/privacy.\n"
        "- *Anthropic* — on plans that include AI-powered features, your uploaded "
        "data may be processed by Anthropic's Claude API to generate insights. "
        "See anthropic.com/privacy.\n"
        "We do not sell, rent, or share your personal data with any other third "
        "party for their own purposes.\n\n"
        "**How long we keep it**\n\n"
        "- *Uploaded datasets*: not retained — discarded at end of session.\n"
        "- *Authentication tokens (OTP)*: automatically expire after 10 minutes "
        "and are purged within 24 hours of expiry.\n"
        "- *Account, profile and subscription records*: retained while your "
        "subscription is active and for up to 6 years thereafter, as required "
        "by UK accounting and tax record-keeping obligations.\n"
        "- *Marketing consent records*: retained until you withdraw consent.\n\n"
        "**Your choices**\n\n"
        "You may withdraw marketing consent or request deletion of your account "
        "data at any time by contacting privacy@coltradata.com.\n\n"
        "**Privacy or data protection questions**: contact privacy@coltradata.com."
    ),

    "gdpr_notice": (
        "**Data controller**: Coltrane Ltd (see registration details above).\n\n"
        "**Lawful basis for processing**\n\n"
        "- *Email, authentication, account profile and subscription data* — "
        "performance of a contract (Article 6(1)(b) UK GDPR): processing is "
        "necessary to provide the service you have subscribed to.\n"
        "- *Profession, industry and usage analytics* — legitimate interests "
        "(Article 6(1)(f) UK GDPR): we have a legitimate interest in understanding "
        "how our product is used across sectors so we can improve it. This data is "
        "always aggregated before analysis; individual profiles are not shared. "
        "You may object to this processing at any time.\n"
        "- *Marketing communications* — consent (Article 6(1)(a) UK GDPR): "
        "we send product updates only to subscribers who explicitly opted in at "
        "account setup. You may withdraw consent at any time by contacting "
        "privacy@coltradata.com.\n"
        "- *Uploaded dataset processing* — performed at your direction as part of "
        "the contracted service. ColtraDataAi acts as a data processor on your "
        "instructions for any personal data contained in files you upload.\n\n"
        "**International transfers**\n\n"
        "Our infrastructure providers (Supabase, Render, Resend, Anthropic) may "
        "process data in the United States or other countries outside the UK/EEA. "
        "Where such transfers occur, they are covered by Standard Contractual "
        "Clauses or equivalent safeguards under UK GDPR.\n\n"
        "**Your rights**\n\n"
        "Under UK GDPR you have the right to: access your personal data; correct "
        "inaccurate data; request erasure ('right to be forgotten'); restrict or "
        "object to processing; data portability; and to withdraw consent at any "
        "time without affecting prior lawful processing. To exercise any of these "
        "rights, contact privacy@coltradata.com. You also have the right to lodge "
        "a complaint with the Information Commissioner's Office (ico.org.uk).\n\n"
        "**If you upload data belonging to other people** (e.g. customer or employee "
        "records), you remain the data controller for that data and ColtraDataAi "
        "acts only as a data processor on your instructions. You are responsible for "
        "having a lawful basis to process that data and for informing the relevant "
        "individuals as required under Articles 13/14 UK GDPR before uploading it."
    ),

    "cookies_notice": (
        "This app uses only the strictly necessary session cookie set by the "
        "Streamlit framework to maintain your session while the app is open. "
        "We do not use analytics, advertising, or third-party tracking cookies. "
        "No cookie consent banner is required as we use no non-essential cookies."
    ),

    "terms_summary": (
        "ColtraDataAi provides automated data cleaning, validation and reporting "
        "only. It does not provide legal, financial, tax, accounting or compliance "
        "advice, and outputs are informational. You remain responsible for "
        "independently reviewing all outputs and obtaining professional advice "
        "before making decisions based on them. By using this app you confirm you "
        "have the right to upload and process any data you submit."
    ),
}
